### ISSUE TITLE
Notice! Read This before anything

### ISSUE THREAD

**Issue by orangethewell** [orangethewell/open-witness-library#4]
Hey!

It's been a long time since I updated this repository. Some things have changed through my life and so my time for working in this project got shortened. So I will leave a short notice here if you came looking for updates.

## The project is abadoned?

No, it's not. Like I said just up there, I'm just been busy, I'm a web development student and an unemployed 19 years old guy. So my priority for now is working in something that can handle me some money to help at home. BUT, I'm organizing my free time to come back to this project and some others related to JW helping apps.

## Some difficulties related to project development

Another thing is that is really hard to work with reverse engineering a entire application that's been up for almost 8 years. Yeah, we got a pretty nice help to decode publications ([take a look here](https://github.com/MrCyjaneK/jwapi/issues/1) and [here](https://github.com/darioragusa/JW-Library-macOS/issues/1#issuecomment-1079989526)) but it still not enough. There's a huge development to ever had a nice working application, like with text color coding and publication organization.

Even then, it's better reverse engineering than developing everything from the ground, at least we have a pretty solid base for it.

I think this is all I have to say, until the next time!

**Comment by orangethewell** [comment]
It seems like a very promising project, at least. The only one I tested was Waydroid, and I had SEVERAL problems running it on Arch. But if ATL moves forward, it will most likely become easier to run the JW Library on Linux.

btw, Tauri, which is the main framework for windowing that I'm using, current support Windows 7, so even Windows users can use the app. 😄

**Comment by Fuseteam** [comment]
ATL (i kinda like to call it antral but that's just me :P) is still moving forward, i'm currently trying to get JWL working https://gitlab.com/tuxecure/jwlibrary_flatpak but it doesn't quite launch yet. But you know what they say, 2 are better than one, so i'm hoping to find others who want to help get it working.

Fun enough the people working on ATL are also on arch.

Also really cool you got it working on windows 7 too :D tho not sure how i feel about friends still using windows 7 xd
